{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "gotrue.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "gotrue.name" . }}
    helm.sh/chart: {{ include "gotrue.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{ if .Values.gotrue.operatorToken }}
  operator-token: {{ .Values.gotrue.operatorToken | b64enc | quote }}
  {{ else }}
  operator-token: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}

  {{ if .Values.gotrue.jwt.secret }}
  jwt-secret: {{ .Values.gotrue.jwt.secret | b64enc | quote }}
  {{ else }}
  jwt-secret: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}

  {{ if .Values.gotrue.jwt.expire }}
  jwt-expire: {{ .Values.gotrue.jwt.expire | b64enc | quote }}
  {{ else }}
  jwt-expire: {{ "3600" | b64enc | quote }}
  {{ end }}

  {{ if .Values.gotrue.jwt.audience }}
  jwt-audience: {{ .Values.gotrue.jwt.audience | b64enc | quote }}
  {{ else }}
  jwt-audience: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
{{- end }}
