apiVersion: v1
kind: Service
metadata:
  name: {{ include "gotrue.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "gotrue.name" . }}
    helm.sh/chart: {{ include "gotrue.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      protocol: TCP
      name: gotrue
  selector:
    app.kubernetes.io/name: {{ include "gotrue.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
